# Generated by Django 4.2.5 on 2023-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(upload_to='static/Recipe_img'),
        ),
    ]
