# Generated by Django 4.1.7 on 2023-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(upload_to='static/cotr/Recipe_img'),
        ),
    ]
